### ISSUE TITLE
The simulation result does not match with the theoretical curve

### ISSUE THREAD

**Issue by ironbean** [Jonathan-Browning/Kappa-Mu-Shadowed-Fading-Matlab#1]
Hi, I tried the program. It seems the simulation result does not match with the theoretical curve with the parameter following the values  shown in the instruction.

**Comment by Jonathan-Browning** [comment]
Hi @ironbean, could you please provide some more details of the specific values that you used? Or are you saying you used the values shown in the example and it doesn't match?  Also are you running it via the files and an instance of MATLAB or did you install it?

**Comment by ironbean** [comment]
Hi @Jonathan-Browning, thanks for the quick responses.  
Yes, I used the value \kappa=3, m=0.6, \mu=3, and \hat{r}=1, which are the same value as those in the example (readme.m). I am running the .m source directly in MATLAB 2020b.  The result is attached.

![1607607006293](https://user-images.githubusercontent.com/64970349/101778521-50d04a80-3b37-11eb-9d91-553e7073f9e7.jpg)

**Comment by Jonathan-Browning** [comment]
Hi @ironbean, I have just checked and I still get the results as provided in the example. It appears the theoretical plot would be incorrect here. In that case it is lines 114-120 in the file: src/ Class/KappaMuShadowed.m. I have checked this against the theoretical PDF from the research paper and it matches exactly. Are you sure there are no other folders shadowing it with another kummer function, which is included here? Have you definitely got the tools folder included in your MATLAB path? Other than this I'm using MATLAB 2018a, so they might be differences there.

**Comment by ironbean** [comment]
Hi, @Jonathan-Browning, It seems I did not configured path correctly. It works just fine now after I re-download the package and reconfigure the path.  Thank you very much for the help.

By the way, do you know how to generate the power random variables following the shadowed \kappa-\mu fading. I would like to simulate the shadowed \kappa-\mu fading channel. Thanks.

**Comment by Jonathan-Browning** [comment]
Hi @ironbean, that's good news! Have you looked at the research papers surrounding the \kappa-\mu fading model? So I have plotted the envelope but if you wanted them as the power then that would be a case of not squaring them (see Cotton's paper: "Second-Order Statistics of \kappa-\mu Shadowed Fading Channels", equation 1). This can be achieved by accessing obj.multipathFading in the class, which I have hidden for simplicity but is accessible, as you can see when I plot the envelope I take the square root of this. I hope that helps.

**Comment by ironbean** [comment]
Hi @Jonathan-Browning, thank you very much for the polite explanation.  I wish you have a nice day and success in the coming days!
